language: ruby
rvm:
  - 2.4.1

before_script:
 - jekyll b # or do this locally and commit

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
  target-branch: master
  local-dir: _site
  repo: Efreestyle/efreestyle.github.io
  email: thibault.lepez@efrei.net
  name: Mr-Monster-0248
  verbose: true