on: 
  release:
    types: [ created ]
    
name: Publish website
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"

  publish:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: crazy-max/ghaction-github-pages@v1
      - name: Sending build folder to Git repo
        with:
            repo: https://github.com/Efreestyle/efreestyle.github.io
            target_branch: master
            build_dir: _site
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
